unit TestuNextRow;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, System.Generics.Collections,
  System.Generics.Defaults, System.Types, System.Classes, uCSVUpdater,
  Functional.Value;

type
  // Test methods for class TCSVUpdater

  TTestNextRow = class(TTestCase)
  strict private
    FStringStream : TStringStream;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure A_Null_Stream_Returns_Empty;
    procedure An_Empty_Row_Returns_Empty;
    procedure Correct_Row_Returns_After_Empty_Field;
    procedure A_Simple_Row_returns_correct_Value;
    procedure Multiple_Rows_Iteratively_Returns_Correct_Values;
    procedure Multiple_Rows_Iteratively_Returns_Correct_From_Large_FileStream;
    procedure A_Row_with_One_Complex_Field_returns_correct_Value;
    procedure A_Row_With_Two_Complex_Fields_returns_correct_Value;
    procedure A_Row_with_Multiple_CR_In_One_Field_Returns_Correct_Value;
  end;

implementation



{ TTestNextRow }

procedure TTestNextRow.An_Empty_Row_Returns_Empty;
var lExpected, lResult : string;
begin
   lResult := NextRow
end;

procedure TTestNextRow.A_Null_Stream_Returns_Empty;
begin
   raise Exception.Create('Not Implemented');

end;

procedure TTestNextRow.A_Row_with_Multiple_CR_In_One_Field_Returns_Correct_Value;
begin
   raise Exception.Create('Not Implemented');

end;

procedure TTestNextRow.A_Row_with_One_Complex_Field_returns_correct_Value;
begin

   raise Exception.Create('Not Implemented');
end;

procedure TTestNextRow.A_Row_With_Two_Complex_Fields_returns_correct_Value;
begin

   raise Exception.Create('Not Implemented');
end;

procedure TTestNextRow.A_Simple_Row_returns_correct_Value;
begin

   raise Exception.Create('Not Implemented');
end;

procedure TTestNextRow.Correct_Row_Returns_After_Empty_Field;
begin

   raise Exception.Create('Not Implemented');
end;

procedure TTestNextRow.Multiple_Rows_Iteratively_Returns_Correct_From_Large_FileStream;
begin
   raise Exception.Create('Not Implemented');

end;

procedure TTestNextRow.Multiple_Rows_Iteratively_Returns_Correct_Values;
begin
   raise Exception.Create('Not Implemented');

end;

procedure TTestNextRow.SetUp;
begin
  inherited;
  self.FStringStream := TStringStream.Create('');
end;

procedure TTestNextRow.TearDown;
begin
  inherited;
  freeAndNil(self.FStringStream);
end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TTestNextRow.Suite);
end.
