unit TestuCSVUpdater;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, System.Generics.Collections,
  System.Generics.Defaults, System.Types, System.Classes, uCSVUpdater,
  Functional.Value;

type
  // Test methods for class TCSVUpdater

  TestTCSVUpdater = class(TTestCase)
  strict private
    FCSVUpdater: TCSVUpdater;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoadHeaders;
    procedure TestLocateRow;
    procedure TestgetRowByValue;
  end;

implementation

procedure TestTCSVUpdater.SetUp;
begin
  FCSVUpdater := TCSVUpdater.Create;
end;

procedure TestTCSVUpdater.TearDown;
begin
  FCSVUpdater.Free;
  FCSVUpdater := nil;
end;

procedure TestTCSVUpdater.TestLoadHeaders;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FCSVUpdater.LoadHeaders;
  // TODO: Validate method results
end;

procedure TestTCSVUpdater.TestLocateRow;
var
  ReturnValue: string;
  AIndex: Integer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FCSVUpdater.LocateRow(AIndex);
  // TODO: Validate method results
end;

procedure TestTCSVUpdater.TestgetRowByValue;
var
  AValue: TValue<System.Object>;
  AHeader: string;
begin
  // TODO: Setup method call parameters
  FCSVUpdater.getRowByValue(AHeader, AValue);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCSVUpdater.Suite);
end.

