unit TestuCSVUpdater;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, System.Generics.Collections,
  System.Generics.Defaults, System.Types, System.Classes, uCSVUpdater,
  Functional.Value;

type
  // Test methods for class TCSVUpdater

  TestTCSVUpdater = class(TTestCase)
  strict private
    FCSVUpdater: TCSVUpdater;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCSVFileName_Contains_full_Path;
    procedure TestCSVUpdater_Header_Row_Contains_Correct_Fields;
    procedure TestCSVUpdater_Row_1_contains_CR;
  end;

implementation

 uses GlenKleidon.CSVUtils;

procedure TestTCSVUpdater.SetUp;
begin
  FCSVUpdater := TCSVUpdater.Create('.\data\fun-stuff.csv');
end;

procedure TestTCSVUpdater.TearDown;
begin
  FCSVUpdater.Free;
  FCSVUpdater := nil;
end;


procedure TestTCSVUpdater.TestCSVFileName_Contains_full_Path;
begin
  check(
     self.FCSVUpdater.Filename.Contains(':'),
     'Filename does not contain full path "' + self.FCSVUpdater.Filename+'"'
  );
end;

procedure TestTCSVUpdater.TestCSVUpdater_Header_Row_Contains_Correct_Fields;
var Expected:string;
    Actual : string;
begin
  Expected :=   'Sequence'#13#10'Date'#13#10'Title'#13#10'Description'#13#10'Comments'#13#10;
  Actual := FCSVUpdater.Headers;
  check(Expected=Actual,'Expected: '+Expected+ #13#10+ 'Actual :'+ Actual);
end;

procedure TestTCSVUpdater.TestCSVUpdater_Row_1_contains_CR;
var Actual: string;
begin
  Actual := self.FCSVUpdater.Row[1];
  check (Actual.Contains(#13#10),'Row 1 did not contain CRLF as Expected.'#13#10 +
          Actual
        );

end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCSVUpdater.Suite);
end.

